# Site settings
title: A blog about lorem ipsum dolor sit amet
description: Hi, I’m Tingting. I like to solve interesting problems with passionate people, and I see life as a diversified portfolio, with every and each new experience as an invaluable asset. I am currently a Co-Founder at Arendil. My friend and I started Arendil to help everyone find and optimize career fulfillments. I am also a participants at the Rotational Leadership Development Program at Sun Life Financial, currently as part of the Investigations team. I solved problems at Facebook as a BI, at Royal Bank of Canada in Capital Markets, at Manulife as an Actuarial Analyst, at Engineers without Borders Waterloo Chapter as an Executive, and many more. 

When I’m not solving problems, I enjoy being immersed in arts and culture. In the past 12 months, I visited eight different countries across three different continents. I was also part of the University of Waterloo A Cappella Ensemble, Muay Thai Club, and Salsa Club. Other interests includes playing the piano, painting, and, pottery. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "yxtzhu.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tingting Zhu
user_description: 
Hi, I’m Tingting. I like to solve interesting problems with passionate people, and I see life as a diversified portfolio, with every and each new experience as an invaluable asset. I am currently a Co-Founder at Arendil. My friend and I started Arendil to help everyone find and optimize career fulfillments. I am also a participants at the Rotational Leadership Development Program at Sun Life Financial, currently as part of the Investigations team. I solved problems at Facebook as a BI, at Royal Bank of Canada in Capital Markets, at Manulife as an Actuarial Analyst, at Engineers without Borders Waterloo Chapter as an Executive, and many more. 
When I’m not solving problems, I enjoy being immersed in arts and culture. In the past 12 months, I visited eight different countries across three different continents. I was also part of the University of Waterloo A Cappella Ensemble, Muay Thai Club, and Salsa Club. Other interests includes playing the piano, painting, and, pottery. 
user_title: Looking to solve interesting problems with passionate people!
email: ting520143@gmail.com
twitter_username: lorem_ipsum
github_username:  yxtzhu
gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
